export interface GlyphKnownStringSpec {
  unicodeString: string;
  aliases: readonly string[];
}

const knownString = (
  unicodeString: string,
  aliases: readonly string[],
): GlyphKnownStringSpec => ({ unicodeString, aliases });

const parsedGlyphKnownStrings = [
  knownString('+', ['+']),
  knownString('−', ['-']),
  knownString('⋅', ['*', 'cdot']),
  knownString('*', ['**', 'ast']),
  knownString('⋆', ['***', 'star']),
  knownString('/', ['//']),
  knownString('\\', ['\\\\', 'backslash', 'setminus']),
  knownString('×', ['xx', 'times']),
  knownString('÷', ['-:', 'div']),
  knownString('⋉', ['|><', 'ltimes']),
  knownString('⋊', ['><|', 'rtimes']),
  knownString('⋈', ['|><|', 'bowtie']),
  knownString('∘', ['@', 'circ']),
  knownString('⊕', ['o+', 'oplus']),
  knownString('⊗', ['ox', 'otimes']),
  knownString('⊙', ['o.', 'odot']),
  knownString('∑', ['sum']),
  knownString('∏', ['prod']),
  knownString('∧', ['^^', 'wedge']),
  knownString('⋀', ['^^^', 'bigwedge']),
  knownString('∨', ['vv', 'vee']),
  knownString('⋁', ['vvv', 'bigvee']),
  knownString('∩', ['nn', 'cap']),
  knownString('⋂', ['nnn', 'bigcap']),
  knownString('∪', ['uu', 'cup']),
  knownString('⋃', ['uuu', 'bigcup']),
  knownString('∫', ['int']),
  knownString('∮', ['oint']),
  knownString('∂', ['del', 'partial']),
  knownString('∇', ['grad', 'nabla']),
  knownString('±', ['+-', 'pm']),
  knownString('∅', ['O/', 'emptyset']),
  knownString('∞', ['oo', 'infty']),
  knownString('ℵ', ['aleph']),
  knownString('∴', [':.', 'therefore']),
  knownString('∵', [":'", 'because']),
  knownString('|...|', ['|...|', '|ldots|']),
  knownString('|⋯|', ['|cdots|']),
  knownString('⋮', ['vdots']),
  knownString('⋱', ['ddots']),
  knownString('∠', ['/_', 'angle']),
  knownString('⌢', ['frown']),
  knownString('△', ['/_\\', 'triangle']),
  knownString('⋄', ['diamond']),
  knownString('□', ['square']),
  knownString('⌊', ['|__', 'lfloor']),
  knownString('⌋', ['__|', 'rfloor']),
  knownString('⌈', ['|~', 'lceiling']),
  knownString('⌉', ['~|', 'rceiling']),
  knownString('C', ['CC']),
  knownString('N', ['NN']),
  knownString('Q', ['QQ']),
  knownString('R', ['RR']),
  knownString('Z', ['ZZ']),
  knownString('=', ['=']),
  knownString('≠', ['!=', 'ne']),
  knownString('<', ['<', 'lt']),
  knownString('>', ['>', 'gt']),
  knownString('≤', ['<=', 'le']),
  knownString('≥', ['>=', 'ge']),
  knownString('m<', ['mlt', 'll']),
  knownString('m>', ['mgt', 'gg']),
  knownString('≺', ['-<', 'prec']),
  knownString('⪯', ['-<=', 'preceq']),
  knownString('≻', ['>-', 'succ']),
  knownString('⪰', ['>-=', 'succeq']),
  knownString('∈', ['in']),
  knownString('∉', ['!in', 'notin']),
  knownString('⊂', ['sub', 'subset']),
  knownString('⊃', ['sup', 'supset']),
  knownString('⊆', ['sube', 'subseteq']),
  knownString('⊇', ['supe', 'supseteq']),
  knownString('≡', ['-=', 'equiv']),
  knownString('≅', ['~=', 'cong']),
  knownString('≈', ['~~', 'approx']),
  knownString('∝', ['prop', 'propto']),
  knownString('and', ['and']),
  knownString('or', ['or']),
  knownString('¬', ['not', 'neg']),
  knownString('⇒', ['=>', 'implies']),
  knownString('if', ['if']),
  knownString('⇔', ['<=>', 'iff']),
  knownString('∀', ['AA', 'forall']),
  knownString('∃', ['EE', 'exists']),
  knownString('⊥', ['_|_', 'bot']),
  knownString('⊤', ['TT', 'top']),
  knownString('⊢', ['|--', 'vdash']),
  knownString('⊨', ['|==', 'models']),
  knownString('↑', ['uarr', 'uparrow']),
  knownString('↓', ['darr', 'downarrow']),
  knownString('→', ['rarr', 'rightarrow']),
  knownString('→', ['->', 'to']),
  knownString('↣', ['>->', 'rightarrowtail']),
  knownString('↠', ['->>', 'twoheadrightarrow']),
  knownString('⤖', ['>->>', 'twoheadrightarrowtail']),
  knownString('↦', ['|->', 'mapsto']),
  knownString('←', ['larr', 'leftarrow']),
  knownString('↔', ['harr', 'leftrightarrow']),
  knownString('⇒', ['rArr', 'Rightarrow']),
  knownString('⇐', ['lArr', 'Leftarrow']),
  knownString('⇔', ['hArr', 'Leftrightarrow']),
  knownString('α', ['alpha']),
  knownString('β', ['beta']),
  knownString('γ', ['gamma']),
  knownString('δ', ['delta']),
  knownString('ε', ['epsilon']),
  knownString('ɛ', ['varepsilon']),
  knownString('ζ', ['zeta']),
  knownString('η', ['eta']),
  knownString('θ', ['theta']),
  knownString('ϑ', ['vartheta']),
  knownString('ι', ['iota']),
  knownString('κ', ['kappa']),
  knownString('λ', ['lambda']),
  knownString('μ', ['mu']),
  knownString('ν', ['nu']),
  knownString('ξ', ['xi']),
  knownString('π', ['pi']),
  knownString('ρ', ['rho']),
  knownString('σ', ['sigma']),
  knownString('τ', ['tau']),
  knownString('υ', ['upsilon']),
  knownString('ϕ', ['phi']),
  knownString('φ', ['varphi']),
  knownString('χ', ['chi']),
  knownString('ψ', ['psi']),
  knownString('ω', ['omega']),
  knownString('Γ', ['Gamma']),
  knownString('Δ', ['Delta']),
  knownString('Θ', ['Theta']),
  knownString('Λ', ['Lambda']),
  knownString('Ξ', ['Xi']),
  knownString('Π', ['Pi']),
  knownString('Σ', ['Sigma']),
  knownString('Φ', ['Phi']),
  knownString('Ψ', ['Psi']),
  knownString('Ω', ['Omega']),
];

const parsedGlyphBrackets = [knownString('{', ['{']), knownString('}', ['}'])];

export const processKnownGlyphString = (knownStringName: string): string => {
  const unicodeString = parsedGlyphKnownStrings.find((spec) =>
    spec.aliases.includes(knownStringName),
  );

  return unicodeString ? unicodeString.unicodeString : knownStringName;
};

export const processGlyphBracket = (bracketString: string): string => {
  const unicodeString = parsedGlyphBrackets.find((spec) =>
    spec.aliases.includes(bracketString),
  );

  return unicodeString ? unicodeString.unicodeString : bracketString;
};
